#!/usr/bin/env python3
"""Block 1 report: five arms at the seam of the two-phase build task.

    python3 v3/ab/harness/ab_build_report.py [--root v3/ab/build] [--out v3/ab/BUILD-REPORT.md]

Per (model, arm): n, hidden tests passed (feature and constraint separately) as mean [95% CI],
re-derived reads in phase 2 (f̂ proxy), tokens at phase-2 start, phase-2 turns and dollars, handover
words. Paired contrasts by (model, rep): A−B (brief vs compaction, the central claim), A−C (brief
vs full transcript, cost), A−D (brief vs nothing), A−E (plugin brief vs naive handover), B−D
(compaction vs nothing). Cohen's d on pooled SD.
"""
import argparse, json, math, statistics as st
from collections import defaultdict
from pathlib import Path
import sys
sys.path.insert(0, str(Path(__file__).resolve().parent))
from ab_report import summ, fmt, t95

ARMS = ["A", "B", "C", "D", "E"]
DESC = {"A": "plugin handoff → fresh session", "B": "carry on, /compact", "C": "carry on, no compaction",
        "D": "fresh session, nothing crosses", "E": "naive handover file, no plugin"}
CONTRASTS = [("A", "B", "brief vs compaction — the central claim (F9, F5, M11)"), ("A", "C", "brief vs full transcript (cost reference)"),
             ("A", "D", "brief vs nothing"), ("A", "E", "plugin brief vs naive handover (isolates the brief + hook)"),
             ("B", "D", "compaction vs nothing"), ("E", "D", "naive handover vs nothing")]


import re

def phase1_writes(d):
    """Files the phase-1 session wrote or edited unprompted (nothing in phase 1 asks for any file)."""
    t = d / "transcript-phase1.jsonl"
    if not t.exists():
        return []
    out = []
    p2 = json.load(open(Path(__file__).resolve().parents[2] / "build" / "phase1-turns.json"))["phase2_prompt"][:60]
    for line in open(t, encoding="utf-8"):
        r = json.loads(line)
        if r.get("role") == "user" and p2 in r.get("text", ""):
            break                                   # arms B/C share one session: stop at the phase-2 prompt
        if r.get("role") == "assistant":
            for m in re.finditer(r'\[tool_use (Write|Edit): \{"file_path": "([^"]+)"', r["text"]):
                out.append(m.group(2).split(d.name + "/")[-1])
    return out


def load(root):
    runs = []
    for prov in sorted(Path(root).glob("*/*/*/provenance.json")):
        d = prov.parent
        if d.name.startswith("void"):
            continue
        p = json.load(open(prov))
        w1 = phase1_writes(d)
        self_memory = [w for w in w1 if not w.startswith("ledgerkit/") and not w.startswith("tests/") and not w.startswith(".governor/")]
        sc = p.get("score") or {}
        if not sc.get("total"):
            continue
        runs.append({"arm": p["arm"], "model": p["model_alias"], "rep": p["rep"],
                     "pass": 100.0 * sc["passed"] / sc["total"], "feat": 100.0 * sc["feature_passed"] / max(1, sc["feature_total"]),
                     "cons": 100.0 * sc["constraint_passed"] / max(1, sc["constraint_total"]),
                     "rederived": p.get("rederived_reads", 0), "tok2": p.get("tokens_in_phase2", 0), "turns2": p.get("turns_phase2") or 0,
                     "cost": p.get("cost_usd", 0), "cost2": p.get("cost_phase2_usd", 0), "turns": p.get("turns", 0),
                     "handover": sum((p.get("handover_words") or {}).values()), "valid": "INVALID" not in " ".join(p.get("verify", [])), "dir": str(d),
                     "self_memory": self_memory})
    return runs


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--root", default="v3/ab/build"); ap.add_argument("--out", default="v3/ab/BUILD-REPORT.md")
    a = ap.parse_args()
    runs = [r for r in load(a.root) if r["valid"]]
    L = ["# Block 1 — reseed from a brief vs carrying on (two-phase build task)", "",
         "Generated by `harness/ab_build_report.py`. Score = hidden tests passed, as a percentage of items (feature and",
         "constraint items separately). Intervals are 95% t-intervals. f̂ proxy = phase-2 Reads of files the phase-1",
         "session had already read. Dollars are the CLI's API-price accounting.", ""]
    if not runs:
        L.append("_No scored runs yet._"); Path(a.out).write_text("\n".join(L) + "\n"); print("empty"); return
    models = [m for m in ("haiku", "sonnet", "opus") if any(r["model"] == m for r in runs)]
    cells = defaultdict(list)
    for r in runs:
        cells[(r["model"], r["arm"])].append(r)
    L += ["## Per cell", "", "| Model | Arm | n | all items % [95% CI] | feature % | constraint % | re-derived reads | tokens at phase-2 start | phase-2 turns | phase-2 $ | total $ | handover words |", "|---|---|---|---|---|---|---|---|---|---|---|---|"]
    for m in models:
        for arm in ARMS:
            rs = cells.get((m, arm))
            if not rs:
                L.append(f"| {m} | {arm} {DESC[arm]} | 0 | not run | | | | | | | | |"); continue
            s = summ([r["pass"] for r in rs])
            L.append(f"| {m} | {arm} {DESC[arm]} | {s['n']} | {fmt(s)} | {st.mean(r['feat'] for r in rs):.0f} | {st.mean(r['cons'] for r in rs):.0f} | "
                     f"{st.mean(r['rederived'] for r in rs):.1f} | {st.mean(r['tok2'] for r in rs)/1e3:.0f}k | {st.mean(r['turns2'] for r in rs):.0f} | "
                     f"${st.mean(r['cost2'] for r in rs):.2f} | ${st.mean(r['cost'] for r in rs):.2f} | {st.mean(r['handover'] for r in rs):.0f} |")
    L += ["", "## Unprompted memory: files the phase-1 session wrote on its own", "",
          "Nothing in phase 1 asks for a file. A session that writes notes anyway carries them across every seam, plugin or not,",
          "which turns the 'nothing crosses' arm into a self-made handover. Counted from the phase-1 transcripts.", "",
          "| Model | Arm | runs | runs that wrote memory files | files (examples) |", "|---|---|---|---|---|"]
    for m in models:
        for arm in ARMS:
            rs = cells.get((m, arm))
            if rs:
                ex = sorted({w for r in rs for w in r["self_memory"]})[:4]
                L.append(f"| {m} | {arm} | {len(rs)} | {sum(1 for r in rs if r['self_memory'])} | {', '.join(ex)} |")
    L += ["", "## Paired contrasts (by model and repeat)", "", "| Contrast | Model | n pairs | Δ all items % [95% CI] | Δ feature % | paired t | wins–ties–losses | Cohen's d | Δ phase-2 $ | Δ re-derived reads |", "|---|---|---|---|---|---|---|---|---|---|"]
    for x, y, why in CONTRASTS:
        for m in models + ["all models"]:
            ms = models if m == "all models" else [m]
            pairs = []
            for mm in ms:
                px = {r["rep"]: r for r in cells.get((mm, x), [])}; py = {r["rep"]: r for r in cells.get((mm, y), [])}
                pairs += [(px[k], py[k]) for k in sorted(set(px) & set(py))]
            if not pairs:
                continue
            d = [u["pass"] - v["pass"] for u, v in pairs]; s = summ(d)
            tstat = (s["mean"] / (s["sd"] / math.sqrt(s["n"]))) if s["n"] > 1 and s["sd"] > 0 else float("nan")
            w = sum(v > 0 for v in d); t_ = sum(v == 0 for v in d); l = sum(v < 0 for v in d)
            xs = [u["pass"] for u, _ in pairs]; ys = [v["pass"] for _, v in pairs]
            sp = math.sqrt((st.variance(xs) + st.variance(ys)) / 2) if len(pairs) > 1 else 0
            cd = (st.mean(xs) - st.mean(ys)) / sp if sp > 0 else float("nan")
            L.append(f"| {x}−{y}: {why} | {m} | {s['n']} | {fmt(s)} | {st.mean(u['feat'] - v['feat'] for u, v in pairs):+.0f} | {tstat:.2f} | {w}–{t_}–{l} | {cd:.2f} | "
                     f"{st.mean(u['cost2'] - v['cost2'] for u, v in pairs):+.2f} | {st.mean(u['rederived'] - v['rederived'] for u, v in pairs):+.1f} |")
    L += ["", "## Reading guide", "",
          "- A−B is the plugin's claim: reseeding from its brief beats letting the session compact. An interval above 0 supports it; one that includes 0 does not.",
          "- A−E separates the plugin's brief and hook from a user writing a handover by hand.",
          "- Re-derived reads are the quantity the plugin's cost rule turns on (f, the chance dropped context is re-read); lower is what the rule predicts for a good brief.",
          "- Constraint items measure the standing rules stated once in phase 1; they are the goal-anchor's territory (F4, M9).", ""]
    Path(a.out).write_text("\n".join(L) + "\n", encoding="utf-8"); print(f"wrote {a.out}: {len(runs)} runs")


if __name__ == "__main__":
    main()
