#!/usr/bin/env python3
"""Aggregate the A/B runs under v3/ab/<arm>/<model>/<run>/ into v3/ab/REPORT.md.

    python3 v3/ab/harness/ab_report.py [--root v3/ab] [--out v3/ab/REPORT.md]

Unit of analysis: one run's judge-averaged score (mean of score.json and score-2.json totals).
Per cell (arm × model × condition): n, mean, SD, 95% t-interval, min–max, cost, turns, handover
words. Paired plugin − baseline by (model, condition, rep): mean difference, 95% t-interval, paired
t, wins. Pooled across models. Cohen's d on the pooled within-cell SD. Judge disagreement reported
separately. Cells with one run report the value and no interval.
"""
import argparse, json, math, statistics as st
from collections import defaultdict
from pathlib import Path

T95 = {2: 12.706, 3: 4.303, 4: 3.182, 5: 2.776, 6: 2.571, 7: 2.447, 8: 2.365, 9: 2.306, 10: 2.262,
       11: 2.228, 12: 2.201, 13: 2.179, 14: 2.160, 15: 2.145, 16: 2.131, 20: 2.093, 25: 2.064, 30: 2.045}

def t95(n):
    if n < 2:
        return math.inf
    return T95.get(n) or T95[max(k for k in T95 if k <= n)]

def load_runs(root):
    runs = []
    for prov in sorted(Path(root).glob("*/*/*/provenance.json")):
        d = prov.parent
        if d.name.startswith("void"):
            continue                                       # quarantined runs are kept for the record, never counted
        sj, sj2 = d / "score.json", d / "score-2.json"
        if not (sj.exists() and sj2.exists()):
            continue
        p = json.load(open(prov))
        s1, s2 = json.load(open(sj))["total"], json.load(open(sj2))["total"]
        cond = d.name.rsplit("-r", 1)[0]
        rep = int(d.name.rsplit("-r", 1)[1]) if "-r" in d.name else 1
        verify_ok = all(("valid" in line and "INVALID" not in line) for line in p.get("verify", []) if line.startswith("segment"))
        runs.append({"arm": p["arm"], "model": p["model_alias"], "cond": cond, "rep": rep, "s1": s1, "s2": s2,
                     "score": (s1 + s2) / 2, "gap": abs(s1 - s2), "cost": p.get("cost_usd", 0), "turns": p.get("turns", 0),
                     "tokens_in": sum(p.get("usage", {}).get(k, 0) for k in ("input_tokens", "cache_creation_input_tokens", "cache_read_input_tokens")),
                     "tokens_out": p.get("usage", {}).get("output_tokens", 0),
                     "handover": sum(p.get("handover_words", {}).values()), "verify_ok": verify_ok, "dir": str(d),
                     "noise_skipped": len(p.get("noise_skipped", [])),
                     "hm": json.load(open(d / "handover-metrics.json"))["handovers"] if (d / "handover-metrics.json").exists() else None})
        r = runs[-1]
        # Anatoly's adjusted score (2026-09-10): a distractor fact carried across a seam costs half a point.
        # Only defined once the run's handovers have been audited.
        r["noise_carried"] = sum(h["noise_facts"] for h in r["hm"]) if r["hm"] else None
        r["adjusted"] = r["score"] - 0.5 * r["noise_carried"] if r["hm"] else None
    return runs

def summ(xs):
    n = len(xs); m = st.mean(xs); sd = st.stdev(xs) if n > 1 else 0.0
    h = t95(n) * sd / math.sqrt(n) if n > 1 else math.inf
    return {"n": n, "mean": m, "sd": sd, "lo": m - h, "hi": m + h, "min": min(xs), "max": max(xs)}

def fmt(s):
    if s["n"] == 1:
        return f"{s['mean']:.1f} (n=1)"
    return f"{s['mean']:.1f} [{s['lo']:.1f}, {s['hi']:.1f}]"

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--root", default="v3/ab")
    ap.add_argument("--out", default="v3/ab/REPORT.md")
    a = ap.parse_args()
    runs = load_runs(a.root)
    L = ["# Plugin A/B — report", "",
         "Generated by `harness/ab_report.py` from the runs on disk. Unit: one run's judge-averaged score",
         "(two independent opus judges). Intervals are 95% t-intervals on the mean. Dollars are the CLI's own",
         "API-price accounting (`total_cost_usd`), notional on a subscription; turns and tokens are actual.", ""]
    if not runs:
        L.append("_No double-judged runs yet._")
        Path(a.out).write_text("\n".join(L) + "\n"); print(f"wrote {a.out} (empty)"); return
    cells = defaultdict(list)
    for r in runs:
        cells[(r["cond"], r["model"], r["arm"])].append(r)
    conds = sorted({r["cond"] for r in runs}); models = [m for m in ("haiku", "sonnet", "opus", "fable") if any(r["model"] == m for r in runs)]
    L += ["## Per cell", "", "| Condition | Model | Arm | n | score mean [95% CI] | SD | min–max | $/run | turns/run | tokens in/out (M/k) | handover words | runs with a skipped distractor |", "|---|---|---|---|---|---|---|---|---|---|---|---|"]
    for cond in conds:
        for m in models:
            for arm in ("baseline", "plugin"):
                rs = cells.get((cond, m, arm))
                if not rs:
                    L.append(f"| {cond} | {m} | {arm} | 0 | not run | | | | | | | |"); continue
                s = summ([r["score"] for r in rs])
                L.append(f"| {cond} | {m} | {arm} | {s['n']} | {fmt(s)} | {s['sd']:.1f} | {s['min']:g}–{s['max']:g} | "
                         f"${st.mean(r['cost'] for r in rs):.2f} | {st.mean(r['turns'] for r in rs):.0f} | "
                         f"{st.mean(r['tokens_in'] for r in rs)/1e6:.1f}/{st.mean(r['tokens_out'] for r in rs)/1e3:.0f} | "
                         f"{st.mean(r['handover'] for r in rs):.0f} | {sum(1 for r in rs if r['noise_skipped'])} of {len(rs)} |")
    L += ["", "## Paired difference, plugin − baseline (paired by model, condition, repeat)", "",
          "A positive mean favours the plugin. Cohen's d uses the pooled within-cell SD of the two arms.", "",
          "| Condition | Model | n pairs | mean diff [95% CI] | paired t | plugin wins–ties–losses | Cohen's d | Δ $/run | Δ turns/run |", "|---|---|---|---|---|---|---|---|---|"]
    pooled = defaultdict(list)
    for cond in conds:
        for m in models + ["all models"]:
            ms = models if m == "all models" else [m]
            pairs = []
            for mm in ms:
                b = {r["rep"]: r for r in cells.get((cond, mm, "baseline"), [])}
                p = {r["rep"]: r for r in cells.get((cond, mm, "plugin"), [])}
                for k in sorted(set(b) & set(p)):
                    pairs.append((p[k], b[k]))
            if not pairs:
                continue
            d = [x["score"] - y["score"] for x, y in pairs]
            s = summ(d)
            tstat = (s["mean"] / (s["sd"] / math.sqrt(s["n"]))) if s["n"] > 1 and s["sd"] > 0 else float("nan")
            w = sum(1 for v in d if v > 0); t_ = sum(1 for v in d if v == 0); l = sum(1 for v in d if v < 0)
            xs = [x["score"] for x, _ in pairs]; ys = [y["score"] for _, y in pairs]
            sp = math.sqrt((st.variance(xs) + st.variance(ys)) / 2) if len(pairs) > 1 else 0
            cd = (st.mean(xs) - st.mean(ys)) / sp if sp > 0 else float("nan")
            dc = st.mean(x["cost"] - y["cost"] for x, y in pairs); dt = st.mean(x["turns"] - y["turns"] for x, y in pairs)
            L.append(f"| {cond} | {m} | {s['n']} | {fmt(s)} | {tstat:.2f} | {w}–{t_}–{l} | {cd:.2f} | {dc:+.2f} | {dt:+.0f} |")
    hm = [r for r in runs if r["hm"]]
    if hm:
        L += ["", "## Adjusted score: half a point off per distractor fact carried across a seam", "",
              "Score − 0.5 × (distractor answers found in the run's handovers). Carrying noise into the next session",
              "is what the penalty targets, so it applies only at seams. Runs without a handover audit are omitted.", "",
              "| Condition | Model | Arm | n | adjusted mean [95% CI] | raw mean | noise carried (mean) |", "|---|---|---|---|---|---|---|"]
        adj_cells = defaultdict(list)
        for r in hm:
            adj_cells[(r["cond"], r["model"], r["arm"])].append(r)
        for cond in conds:
            for m in models:
                for arm in ("baseline", "plugin"):
                    rs = adj_cells.get((cond, m, arm))
                    if not rs:
                        continue
                    s_ = summ([r["adjusted"] for r in rs])
                    L.append(f"| {cond} | {m} | {arm} | {s_['n']} | {fmt(s_)} | {st.mean(r['score'] for r in rs):.1f} | {st.mean(r['noise_carried'] for r in rs):.1f} |")
        L += ["", "Paired adjusted difference, plugin − baseline:", "", "| Condition | Model | n pairs | mean diff [95% CI] |", "|---|---|---|---|"]
        for cond in conds:
            for m in models + ["all models"]:
                ms = models if m == "all models" else [m]
                d = []
                for mm in ms:
                    b = {r["rep"]: r for r in adj_cells.get((cond, mm, "baseline"), [])}
                    p_ = {r["rep"]: r for r in adj_cells.get((cond, mm, "plugin"), [])}
                    d += [p_[k]["adjusted"] - b[k]["adjusted"] for k in sorted(set(b) & set(p_))]
                if d:
                    L.append(f"| {cond} | {m} | {len(d)} | {fmt(summ(d))} |")
        L += ["", "## What the handovers carried (context-appropriate facts)", "",
              "Per handover: canon facts present (of 112, one opus audit per handover) and distractor answers present",
              "(of 8 at seam 1, 16 at seam 2, checked by token). Share = story / (story + noise). Means over runs and seams.", "",
              "| Condition | Model | Arm | runs audited | handover words | story facts /112 | noise facts | context-appropriate share |", "|---|---|---|---|---|---|---|---|"]
        for cond in conds:
            for m in models:
                for arm in ("baseline", "plugin"):
                    rs = [r for r in hm if r["cond"] == cond and r["model"] == m and r["arm"] == arm]
                    if not rs:
                        continue
                    hs = [h for r in rs for h in r["hm"]]
                    sh = [h["context_appropriate_share"] for h in hs if h["context_appropriate_share"] is not None]
                    L.append(f"| {cond} | {m} | {arm} | {len(rs)} | {st.mean(h['words'] for h in hs):.0f} | {st.mean(h['story_facts'] for h in hs):.1f} | "
                             f"{st.mean(h['noise_facts'] for h in hs):.1f} | {st.mean(sh):.2f} |" if sh else f"| {cond} | {m} | {arm} | {len(rs)} | | | | |")
    L += ["", "## Judge disagreement", ""]
    gaps = [r["gap"] for r in runs]
    L.append(f"|judge 1 − judge 2| over {len(gaps)} runs: mean {st.mean(gaps):.2f}, median {st.median(gaps):.1f}, max {max(gaps)}. "
             "Run-to-run spread (the SD column above) is the other noise source; keep them apart when reading a difference.")
    bad = [r for r in runs if not r["verify_ok"]]
    L += ["", "## Verification", "", f"{len(runs) - len(bad)} of {len(runs)} scored runs passed transcript verification."]
    for r in bad:
        L.append(f"- NOT verified: {r['dir']}")
    L += ["", "## Reading guide", "",
          "- A paired interval that excludes 0 supports a real effect of the plugin at this n; one that includes 0 means these runs cannot tell the arms apart.",
          "- The per-cell intervals are wide by construction at n = 5; the paired table is the test, because it removes the model's own run-to-run level.",
          "- Cost columns are what the plugin costs in turns and API-equivalent dollars over the same reading; a score gain must be read against them.", ""]
    Path(a.out).write_text("\n".join(L) + "\n", encoding="utf-8")
    print(f"wrote {a.out}: {len(runs)} runs")

if __name__ == "__main__":
    main()
