#!/usr/bin/env python3
"""Test 4 report: a new topic mid-work — same session vs the plugin's new-session flow.

    python3 v3/ab/harness/ab_topic_report.py [--root v3/ab/topic] [--out v3/ab/TOPIC-REPORT.md]

Per (model, arm): topic-B hidden tests %, ledgerkit phase-2 hidden tests %, phase-2 re-derived reads,
cost of topic B, cost of phase 2, total cost. Paired contrasts N−S (plugin flow vs one plain session),
N−P (plugin flow vs plugin loaded but ignored), P−S (plugin loaded vs not, same session).
"""
import argparse, json, math, statistics as st
from collections import defaultdict
from pathlib import Path
import sys
sys.path.insert(0, str(Path(__file__).resolve().parent))
from ab_report import summ, fmt

ARMS = ["S", "P", "N"]
DESC = {"S": "same session, no plugin", "P": "same session, plugin + goal (advisories ignored)", "N": "plugin: conclude → fresh session for B → merge for phase 2"}
CONTRASTS = [("N", "S", "plugin new-session flow vs one plain session"), ("N", "P", "plugin flow vs plugin loaded but ignored"), ("P", "S", "plugin loaded vs not, same session")]


def load(root):
    runs = []
    for prov in sorted(Path(root).glob("*/*/*/provenance.json")):
        d = prov.parent
        if d.name.startswith("void"):
            continue
        p = json.load(open(prov)); sc = p.get("score") or {}
        if not sc:
            continue
        a, b = sc["ledgerkit"], sc["topic_b"]
        runs.append({"arm": p["arm"], "model": p["model_alias"], "rep": p["rep"], "a": 100.0 * a["passed"] / a["total"], "b": 100.0 * b["passed"] / b["total"],
                     "rederived": p.get("rederived_reads", 0), "cost": p.get("cost_usd", 0), "cost_b": p.get("cost_topic_b_usd", 0), "cost2": p.get("cost_phase2_usd", 0),
                     "turns": p.get("turns", 0), "valid": "INVALID" not in " ".join(p.get("verify", [])), "dir": str(d)})
    return runs


def main():
    ap = argparse.ArgumentParser(); ap.add_argument("--root", default="v3/ab/topic"); ap.add_argument("--out", default="v3/ab/TOPIC-REPORT.md")
    a = ap.parse_args()
    runs = [r for r in load(a.root) if r["valid"]]
    L = ["# Test 4 — a new topic mid-work: same session, or a new session as the plugin advises", "",
         "Generated by `harness/ab_topic_report.py`. Sequence: ledgerkit investigation → topic B (shift-roster task, separate",
         "directory, 10 hidden tests) → ledgerkit phase 2 (30 hidden tests). Percent of items passed; 95% t-intervals.", ""]
    if not runs:
        L.append("_No scored runs yet._"); Path(a.out).write_text("\n".join(L) + "\n"); print("empty"); return
    models = [m for m in ("haiku", "sonnet", "opus") if any(r["model"] == m for r in runs)]
    cells = defaultdict(list)
    for r in runs:
        cells[(r["model"], r["arm"])].append(r)
    L += ["## Per cell", "", "| Model | Arm | n | topic B % [95% CI] | ledgerkit phase 2 % [95% CI] | re-derived reads | $ topic B | $ phase 2 | $ total | turns |", "|---|---|---|---|---|---|---|---|---|---|"]
    for m in models:
        for arm in ARMS:
            rs = cells.get((m, arm))
            if not rs:
                L.append(f"| {m} | {arm} {DESC[arm]} | 0 | not run | | | | | | |"); continue
            sb, sa = summ([r["b"] for r in rs]), summ([r["a"] for r in rs])
            L.append(f"| {m} | {arm} {DESC[arm]} | {len(rs)} | {fmt(sb)} | {fmt(sa)} | {st.mean(r['rederived'] for r in rs):.1f} | ${st.mean(r['cost_b'] for r in rs):.2f} | "
                     f"${st.mean(r['cost2'] for r in rs):.2f} | ${st.mean(r['cost'] for r in rs):.2f} | {st.mean(r['turns'] for r in rs):.0f} |")
    L += ["", "## Paired contrasts (by model and repeat)", "", "| Contrast | Model | n | Δ topic B % [95% CI] | Δ phase 2 % [95% CI] | Δ $ total | Δ re-derived |", "|---|---|---|---|---|---|---|"]
    for x, y, why in CONTRASTS:
        for m in models + ["all models"]:
            ms = models if m == "all models" else [m]; pairs = []
            for mm in ms:
                px = {r["rep"]: r for r in cells.get((mm, x), [])}; py = {r["rep"]: r for r in cells.get((mm, y), [])}
                pairs += [(px[k], py[k]) for k in sorted(set(px) & set(py))]
            if not pairs:
                continue
            db = summ([u["b"] - v["b"] for u, v in pairs]); da = summ([u["a"] - v["a"] for u, v in pairs])
            L.append(f"| {x}−{y}: {why} | {m} | {len(pairs)} | {fmt(db)} | {fmt(da)} | {st.mean(u['cost'] - v['cost'] for u, v in pairs):+.2f} | {st.mean(u['rederived'] - v['rederived'] for u, v in pairs):+.1f} |")
    Path(a.out).write_text("\n".join(L) + "\n", encoding="utf-8"); print(f"wrote {a.out}: {len(runs)} runs")


if __name__ == "__main__":
    main()
